### ISSUE TITLE
Vote transaction

### ISSUE THREAD

**Issue by MButcho** [elastos/Elastos.ELA#1631]
Hi @bocheng0000 ,
I am developing Elastos Light Wallet with Ledger integration. We have problem with Ledger limitation of around 1010 bytes per transaction which causes limitation to vote max 22 nodes. 

Is there a way to create staging transaction which would consists of 2 signed transactions, both with 18 nodes each and then sign the staging transaction again that would be less than 1010 bytes?

@kpachhai proposed to find a way to combine two different transactions into a single transaction (both deconstruction and construction).

Thank you

MButcho

**Comment by bocheng0000** [comment]
Thanks for your work @MButcho 

I think this way will not work.

Can we sign the digest using Ledger? If so, we can vote as follow:
1. create the vote transaction
2. calculate the digest of the transaction
3. sign the digest using ledger
4. add the signature got above to the transaction
5. publish the transaction

**Comment by MButcho** [comment]
Hi @bocheng0000,
can you point me on how to calculate digest of the vote transaction in java? I will test it out.

Also the digest is calculated from raw or encoded TX? And when calculate digest you basically do: encodedTX+signed digest by Ledger and send it?

Thank you very much for help :)

**Comment by bocheng0000** [comment]
Yeah, we can get the digest by calculating the SHA256 of the transaction's raw data.

I suggestion you to have a try as follow:
1. get the raw data by `encodedTxHex = TxTranscoder.encodeTx(tx, false);`
2. get the digest by `hash = getHash(bufferHex);` 
3. get signature by `signature = curve.sign(hash, privateKey, null);`
4. add signature to the transaction by `addSignatureToTx = (tx, publicKey, signature)`

**Comment by coranos** [comment]
signing just the hash is a huge security risk and ledger will not allow you to code an app like that.

all parts of the tx need to be viewable on the device. Otherwise you could be signing the digest of 'send all my funds to kucoin' instead of 'set my votes'.

there's no way to sign a transaction over 1kb on the ledger. please reduce the transaction size, it's way bigger than any reasonable tx size (300 bytes max).

**Comment by bocheng0000** [comment]
Close this issue as we can't reduce the size of the vote transaction for now.

**Comment by MButcho** [comment]
@bocheng0000 got another idea on voting 36 nodes with Ledger. What if we split the voting TX into 2 pieces. 
1st TX will be regular sending TX without candidates, send to Ledger and Sign it. 
2nd TX will be candidates only, send to Ledger and Sign it. 
Then create regular voting TX as it is now, with both sending and candidates and add those 2 signatures joined and send.

Cheers

**Comment by coranos** [comment]
A variant of that would work. Currently, any TX resets the candidate list.
If the code was changed so that vote transactions were additive rather than replacements, then you could do two TXs.

For Example:
Current Code:
- TX 1 votes for candidate A. List of candidates is A.
- TX 2 votes for candidate B. List of candidates is B.
- TX 3 votes for no candidates. List of candidates is empty.

New way:
- TX 1 votes for candidate A. List of candidates is A.
- TX 2 votes for candidate B. List of candidates is A,B.
- TX 3 votes for no candidates. List of candidates is empty.

Then you could vote for as many candidates as you want, and it would not be limited by the ledger hardware.
A vote for 'no candidates' would still reset the candidate list to empty.

**Comment by MButcho** [comment]
@bocheng0000 can you check Coranos proposal?
