### ISSUE TITLE
Sidechain Merge Mining

### ISSUE THREAD

**Issue by tomsej** [elastos/Elastos.ELA#223]
I am also curious about merged mining. Usually the biggest disadvantage of merged mining is that additional daemon has to run on miners machine. It of course uses some cpu, space, memory, io and bandwidth. Big barrier for miners is also that most of daemons codebase are not maintained. So not a lot of big players are not willing to allow merge mining. If I would like to create my own Elastos sidechain with PoW so I would be able to merge mine alongside with Elastos, do I need to convince miners to deploy my own daemon or is the situation different to bitcoin merge mining? Thanks a lot

**Comment by kpachhai** [comment]
@AlexpanXX Could you answer this?

**Comment by yz89** [comment]
Sidechain merged mining is another design which different from bitcoin merged mining.

1. Miners do not need to run side chain nodes, but only need to run the main chain deamon, which can be merged mining normally
2. Compared with ordinary merged mining, which puts auxblock hash into coinbase, the merged mining of sidechain sends a sidechainpow transaction to the main chain by arbiter. https://github.com/elastos/Elastos.ELA/blob/dev/core/payloadsidechainpow.go
3. In order to ensure the overall safety of the main chain and side chains, only arbiter can send sidechainpow transaction. The side chain block is generated by arbiter nodes. (arbiter is similar to the delegator of DPOS)
4. Your side chain only needs to convince arbiter to run your side chain node and then can be merged mining by arbiter.

Arbiter is an independent repo, and go public soon.

**Comment by tomsej** [comment]
Thanks a lot!!
