### ISSUE TITLE
Ela block question

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.ELA#37]
So, according to whitepaper, a single ela block can have unlimited number of transactions unlike btc that can only hold up to 1 MB of transactions at the moment. How did the dev team address the drawbacks resulting from block size limit removal? Indeed, removing the size limit of blocks would cause increasing computational efforts by the miners and several other issues I'm assuming?

**Comment by AlexpanXX** [comment]
We have a block size limit parameter `MaxBlockSize` in the config.json file, now this parameter is se to 8000000, which means nearly 8 MB.

**Comment by veivavelevetto** [comment]
Thank you for replying, I'm the one who posted this question on reddit that was kindly reported here by @kpachhai . I'm not a developer, just blockchain enthusiast. @AlexpanXX so the block size is not at all unlimited. Being different from bitcoin's one, is there the possibility of troubles in the rate of Elastos's block issuing? It would be nice if in the next future someone could provide in the whitepaper a detailed explaination of what merged mining is, because I'm not sure of having understood who it works. Are there other projects adopting this strategy?

**Comment by veivavelevetto** [comment]
Could someone answer my questions please?

**Comment by yz89** [comment]
Yes, [namecoin](https://github.com/namecoin/namecoin-core) adopted merged mining. 
Refer to the merged mining details here https://en.bitcoin.it/wiki/Merged_mining_specification

**Comment by kpachhai** [comment]
Closing this as the original question has been answered.
